### ISSUE TITLE
Did you manage to deploy this to firebase?

### ISSUE THREAD

**Issue by Evertt** [reepolee/svelte-kit-tailwind-jit#3]
I see that you have `functions` in gitignore, which could mean that you've been working on getting this to deploy on firebase. Did you manage? I also tried it, but I'm getting errors. If you figured out how, can you tell me how? 😇

**Comment by alesvaupotic** [comment]
No, I am not using firebase, but I am working on Cloudflare Pages. Will report once I get them running.
