### ISSUE TITLE
windicss version

### ISSUE THREAD

**Issue by joshua1** [reepolee/svelte-kit-tailwind-jit#4]
Weldon Reepolee team on this starters.  I wanted to ask if you can create one for sveltekit but using the windicss setup . Thanks

**Comment by alesvaupotic** [comment]
Working on one as we speak.

**Comment by joshua1** [comment]
Thanks @alesvaupotic

**Comment by alesvaupotic** [comment]
@joshua1 Willing to test https://github.com/reepolee/svelte-kit-windi ?

**Comment by joshua1** [comment]
On it
